name: Build and Push Docker Image
on:
  push:
    branches:
      - master
jobs:
  test-and-build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
    - name: Test with pytest api
      run: |
        python3 -m pytest run_test.py

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/axe-test-web-server:${{ github.sha }}
