name: Build and Push Docker Image
on:
  push:
    branches:
      - master
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/axe-test-web-server:${{ github.sha }}

  testing:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: docker run
          run: docker run --name=mycontainer -p 5000:5000 ${{ secrets.DOCKERHUB_USERNAME }}/axe-test-web-server:${{ github.sha }
      - name: curl Intergrate Test
          run: curl http://127.0.0.1:5000/api/total/abcd
      - name: Docker Stop
          run: Docker stop mycontainer
      - name: Docker Container Delete
          run: Docker container rm mycontainer
